lib/index.js, tests/assemble-app-test.js, tests/helpers/app-helper.js, tests/helpers/index.js
Makes assemble-app-test.js easier to read in preparation for testing more API methods.
Also, the 'returns null if a redirect doesn't exist' case was failing if there was a nonempty `dump.rdb` file from a separate redis-server run that contained relocation data for `/foo`. Since there doesn't appear to be a redis-server flag to instruct redis not to load the dump file, specifying a nonexistent dump file resolves this issue.
=> Extract AppHelper, avoid RedisClient test failure on start

lib/index.js, lib/redirect-db.js, tests/app-test.js, tests/redirect-db-test.js
This will enable the API to use the same underlying `getRedirect()` method without API access counting towards the redirect total.
=> RedirectDb: Make recordAccess an option

lib/redirect-db.js, lib/redis-client.js, tests/redirect-db-test.js, tests/redis-client-test.js
After starting to write the API router, I realized it would be better to distinguish between forbidden or disallowed operations (HTTP 403 and related) and internal errors (HTTP 500).
RedisClient now returns a Boolean if an operation was carried out successfully, based on whether the result matched what was expected; and throws Errors only when an operation failed.
RedirectDb now returns a rejected Promise containing a string on forbidden/disallowed operations and an Error if a client operation failed or an unexpected internal error occurred.
=> RedisClient,RedirectDb: Change interface contracts

lib/index.js, tests/app-test.js
Also contains minor internal refactorings to share the error handler implementation between the API router and the other app routes.
=> Add API router, first handler for /info

config.json, lib/auth.js, lib/auth/google.js, lib/index.js, tests/app-test.js, tests/auth-test.js, tests/config-test.js, tests/helpers/test-config.json
I hadn't noticed I'd spelled `saveUninitialized` incorrectly until a new test emitted an express-session deprecation warning. This change also explicitly sets `sessionStore` to `null` when it's `undefined`.
Renamed `GOOGLE_REDIRECT_URL` to `GOOGLE_CALLBACK_URL` for semantic clarity.
Also, while trying to run the app with actual Google OAuth authentication, the OAuth callback request would hang. I eventually realized it was because I'd written `auth.serializeUser()` and `auth.deserializeUser()` as factory functions, but was passing them directly to `passport.serializeUser()` and `passport.deserializeUser()`. Invoking the factory functions resolved the hangup.
To avoid such confusion in the future, I've renamed the factory functions to `makeUserSerializer()` and `makeUserDeserializer()`.
=> Rename variables and functions, fix (de)serializeUser bug

.gitignore, index.js, lib/auth/test.js, lib/config.js, lib/index.js, package.json, scripts/serve, scripts/test, tests/app-test.js, tests/auth-test.js, tests/config-test.js, tests/helpers/index.js, tests/redis-client-test.js, tests/smoke-test.js
[Passport](http://passportjs.org/) integration is finally integrated and fully tested. The following article provided the key insight necessary for testing this integration, which was to ditch supertest.agent (which wasn't working for me) and capture the session cookie instead:
- ["Testing Authenticated Requests with Supertest" by Juha Hytönen](https://medium.com/@juha.a.hytonen/testing-authenticated-requests-with-supertest-325ccf47c2bb)
A server configured with actual Google application credentials can now successfully serve the homepage, API endpoints, and redirects, run via:
```sh
$ node ./index.js path/to/config.js
```
Also adds [morgan](https://www.npmjs.com/package/morgan) for request logging.
=> Integrate and test passport authentication

.eslintignore, .gitignore, .travis.yml, package.json, public/app.js, public/index.html, public/tests/index.html, public/tests/lib.js, public/tests/tests.js, scripts/lint, scripts/test.d/browser, tests/helpers/phantomjs.js
This ensures that the browser tests are run as part of the Travis CI build. Will likely be absorbed into `./go test` in the near future. A future change will also introduce browser test coverage, likely following the guidance of: [Measuring Client-Side JavaScript Test Coverage With Istanbul](https://blog.engineyard.com/2015/measuring-clientside-javascript-test-coverage-with-istanbul)
This also contains a couple of other minor touch-ups to the existing client-side app code.
=> Add `./go tests browser` using mocha-phantomjs

.travis.yml, public/tests/index.html, scripts/test.d/browser, tests/helpers/phantomjs.js, tests/helpers/pick-unused-port
Closes #23. Adds the `tests/helpers/pick-unused-port` Node script to facilitate `scripts/test.d/browser` running `live-server` on a port allowed by Travis CI.
=> Pick an unused port to run ./go test browser

public/tests/coverage.html, scripts/test.d/browser
Turned out that if I ran `./go test --coverage` before `./go serve --test`, the in-browser Mocha test page would be broken because `public/tests/generated/index.js` would be the incorrect version.
=> test: Keep browser test bundle separate

scripts/test
I noticed when a test was failing that coverage was successfully collected, but the error message from `./go test --coverage` seemed to contradict that fact. Updated the message to indicate that either the test suite OR coverage collection failed.
=> scripts/test: Improve ./go test --coverage error

.eslintignore, README.md, public/app.js, public/index.html, public/tests/coverage.html, public/tests/index.html, public/tests/lib.js, public/tests/tests.js, public/tests/vendor/sinon.js, tests/app-test.js
This gets the app loader and the first implementation of the URL fragment router in place.
=> Begin user interface implementation with app loading and URL fragment router

public/app.js, public/tests/coverage.html, public/tests/index.html, public/tests/tests.js, tests/helpers/browser.js
Inspired by the example from http://vanilla-js.com/ but Promise-ified and a bit more robust, while much more lightweight than jQuery's fadeIn/fadeOut. In preparation for flashing success and failure messages when creating or updating a link.
=> app: Implement fade function for flash elements

public/app.js, public/tests/tests.js
Previously, the opacity to go immediately to zero on the first call.
=> app: Fix incorrect fade out conditional

public/app.js, public/index.html, public/tests/tests.js
A future commit will add an automated end-to-end test to cover the actual XHR POST behavior, but confirmed manually that end-to-end behavior works.
Also establishes the convention of attaching a `Promise` to the click target as the `done` property to facilitate testing.
=> app: createLinkClick handler

scripts/test, scripts/test.d/browser
The refactor should help make the script more readable. Adding the `--coverage` flag enables the collection of reports just for browser test coverage, rather than for the entire project.
=> test browser: Refactor, add --coverage flag

.istanbul.yml, scripts/test
Now Istanbul will provide a unified summary of both backend and frontend test coverage to the console at the end of `./go test --coverage`. Also, `./go test browser --coverage` will also show a browser-specific summary.
Also allows the collection of coverage for a subset of backend tests.
=> Update coverage configuration

tests/helpers/index.js, tests/smoke-test.js
`launchAll()` will make it easier to write more system-level/end-to-end tests.
=> tests/helpers: Extract launchServer, launchAll

lib/auth/test.js, tests/app-test.js, tests/auth-test.js
Realized it would be handy to have the test authentication implementation controlled via the `URL_POINTERS_TEST_AUTH` environment variable. Makes stubbing the `TestStrategy.authenticate` method superfluous.
=> auth/test: Implement authenticate using env var

package.json, scripts/test.d/browser
This will require that the user have phantomjs already installed; will update scripts/setup to ensure this in a future commit. That said, this should speed up Travis builds slightly by allowing it to use its default phantomjs rather than having to download the version used by mocha-phantomjs.
=> test browser: Switch to mocha-phantomjs-core

index.js, lib/auth/test.js, tests/app-test.js, tests/auth-test.js
Initial attempts to get the end-to-end test working were thwarted because the previous `TestStrategy` didn't actually cause a session to get created, leading to an endless redirect loop. These changes make the test authentication strategy more robust, and enable the initial end-to-end test to function successfully.
Also started introducing arrow functions into the code base. I may go through and update all functions to be arrow functions in a future commit.
=> auth/test: Enable sessions via redis

index.js, tests/helpers/index.js, tests/helpers/system-test-config.json, tests/smoke-test.js
The test server can now launch using a dynamically-selected port, rather than always defaulting to 3000.
The call to `setTimeout()` was vestigial from trying to resolve Travis build failures in #15; should've been removed when the test suite timeout was increased to 5000ms in #18.
Also added smoke tests to cover the different ways of passing a config file to the main process, as well as to check startup failure due to a bad configuration. The environment variable-only branch isn't fully checked, as it's currently not possible to specify the entire configuration that way, though that may change eventually.
=> tests/helpers: Launch with dynamic port, add tests

public/app.js, public/tests/redirect-target.html, tests/end-to-end.js
Will get it to work on PhantomJS and Safari later, as well as add a unit test for the new behavior whereby the newly-created link is focused. (There's a known issue and fix for the Firefox `sendText()` behavior that hasn't yet made its way into selenium-webdriver.)
Also grateful for the following articles to light my way a little better:
- https://team.goodeggs.com/getting-started-with-selenium-webdriver-for-node-js-f262a00c52e1
- http://www.techinsight.io/review/devops-and-automation/browser-automation-using-selenium-webdriver-and-nodejs/
=> end-to-end: Refactor for Chrome, focus new link

.travis.yml, scripts/setup, scripts/test, scripts/test.d/end-to-end
Since `./go setup` should do everything necessary to set up the environment and run the tests, it seems like a good idea to run it as the Travis CI test command. Also updated some of the help text for `./go test` and `./go test end-to-end`.
=> setup: Install PhantomJS if missing; use for CI

scripts/lib/coverage, scripts/setup, scripts/test, scripts/test.d/backend, scripts/test.d/browser, scripts/test.d/end-to-end
The scripts are now a bit easier to understand and maintain, since `./go test` now runs all of the backend, browser, and end-to-end tests, optionally with coverage enabled. Each of the backend, browser, and end-to-end test suites have been split into their own separate scripts, with the backend and browser tests using a common `scripts/lib/coverage` module.
Previously `./go test` defaulted to running the backend tests, included the browser tests when run with `--coverage`, and didn't run the end-to-end tests at all.
=> scripts: Revamp `./go test`, `./go setup`

go, scripts/setup, scripts/test, scripts/test.d/end-to-end, scripts/test.d/server, tests/end-to-end/end-to-end.js, tests/server/app-test.js, tests/server/auth-test.js, tests/server/config-test.js, tests/server/redirect-db-test.js, tests/server/redis-client-test.js, tests/server/smoke-test.js
The structure and scope of the tests and their accompanying scripts are now easier to follow. `scripts/test` is more streamlined and robust. `./go lint` and `./go test` are out of the
critical section of `./go setup`, and logging across both `./go setup` and `./go test` is much improved.
=> Rename `./go test server`, move tests, improve `./go setup` and `./go test`

public/app.js, public/tests/tests.js
Per the TODO added in #47 and removed in this commit. The behavior was already covered by the end-to-end test, but still needed a unit test.
=> app: Add unit test for result link focus

public/tests/index.html, public/tests/lib.js, scripts/serve, tests/helpers/coverage-middleware.js
Turns out it's really easy to do this with istanbul-middleware, and super convenient and cool!
Also extracted a separate matcher function for istanbul-middleware. Doesn't make a functional difference, but better follows the API.
=> Generate live browser test coverage report

.config/karma.conf.js
Accidentally set this to `false` before. Removing it and allowing it to default to `true` restores the intended behavior.
=> karma: Re-enable autoWatch

.config/karma.conf.js, scripts/lib/coverage, scripts/setup
Fixes `./go test --coverage` and updates the Karma config on Linux, and checks for `redis-server` as a `./go setup` prerequisite.
=> Updates to ensure smooth setup on Linux

go, scripts/lib/setup, scripts/setup, scripts/setup.d/karma
Adds `./go setup karma`, sets up Windows for browser-only development (using `./go setup karma`), and disables MSYS2 POSIX path conversion (see mbland/go-script-bash#176).
=> Enable browser-only setup via Karma (specifically for Windows)

go, scripts/test.d/browser
Turns out setting `MSYS_NO_PATHCONV='true'` and `MSYS2_ARG_CONV_EXCL='*'` at the top level was a bad idea, as it breaks `npm install`. So mbland/go-script-bash#176 should be closed.
=> go, test browser: Move MSYS2 POSIX path setting

.config/karma.conf.js, scripts/setup, scripts/test
Turns out the `karma start --single-run` flag was there all along.
`KARMA_BROWSERS` is handy for limiting the number of browsers open at once, in case you want or need to do so.
=> karma: Remove KARMA_SINGLE_RUN, add KARMA_BROWSERS

.gitignore, scripts/lib/coverage, scripts/setup, scripts/test.d/browser, tests/helpers/coverage-server
On Windows Subsystem for Linux, PhantomJS appears to crash when using `live-server`. As widely reported, the same thing happens with Karma, which can be observed by trying to run Karma in this project. It seems to be related to JavaScript that attempts to force a browser reload (possibly because of WebSockets, perhaps?).
This change resolves the issue for `./go test browser --single-run` by supplying a small, hand-written test server instead.
Also adds the `COVERAGE_REPORT_SERVER` environment variable. By setting this environment variable to `false`, the script won't open a browser window after coverage collection. With it set to `true`, it will open it using `live-server`, which is preferable to opening it with xdg-open on Windows Subsystem for Linux. When it's empty (and `CI` isn't …
=> Resolve `./go test browser --single-run` issues on Windows Subsystem for Linux

.config/env.local, .gitignore, go, package.json, scripts/lib/karma, scripts/setup, scripts/test
`.config/env.local` enables relatively easy local configuration, and is listed in `.gitignore` to avoid committing local modifications.
Also, Karma is disabled completely on Windows Subsystem for Linux for the reasons described in the `.config/env.local` header comments.
=> test: Add .config/env.local, disable Karma on WSL

scripts/setup
Since `scripts/lib/karma` depends on the `is-wsl` npm, we need to make sure to import that module only after `npm install` has run.
=> setup: Import karma module after npm install

.config/env.template, go
The original intention of adding .config/env.local to .gitignore was to prevent local changes to the file from getting checked in. However, .gitignore will not ignore files actually checked into the repository.
With this change, the convention is now to copy .config/env.template to .config/env.local before making changes. `./go` now checks for this file before attempting to source it.
=> Move .config/env.local to .config/env.template

scripts/lib/coverage
`./go test --coverage` serves results via live-server when `COVERAGE_REPORT_SERVER='true'`. Previously, the script would exit with a signal status when the user would enter CTRL-C to terminate the server, regardless of whether the test suite actually passed or failed.
`./go test --coverage` now exits with the correct status when the user terminates the server. It also emits informational messages when live-server is started and terminated.
=> test --coverage: Shut down live-server gracefully

scripts/test.d/browser, tests/helpers/browser-test-server
The test server is used for all `./test browser --single-run` modes, not just when running with `--coverage`.
Also, setting the middleware only when `COVERAGE_RUN=true` doesn't affect output much, since assertion failures via PhantomJS don't produce stack trace output, but still feels better to have this mechanism in place.
=> Rename browser-test-server, use middleware if COVERAGE_RUN=true

.travis.yml, package-lock.json, scripts/setup
Somehow this file got into a weird state, causing breakages across platforms. Couldn't find any online banter about it, but upgrading to npm 5.0.1, removing the file, and doing a fresh re-install resolved the problem.
=> npm: Fix package-lock.json

package-lock.json
Seems a few packages are no longer necessary. Hopefully this will be the last package-lock.json churn for a while.
=> npm install: Update package-lock.json

.travis.yml
Seems a little more correct than a plain `npm install -g npm`.
=> travis: Set npm version spec to ^5.0.1

package-lock.json
Turns out `./go test browser` can't run without these. They may have been removed before because I hadn't done a `rm -rf node_modules` before a fresh `npm install`.
=> npm: Restore packages from 3dc95a9

tests/helpers/index.js
The "Ready to accept connections" string changed in v4.0.0, breaking the previous `launchRedis` implementation.
=> tests: Fix launchRedis for redis-server v4

.gitignore, tests/end-to-end/end-to-end.js
By default, `takeScreenshot` will write `screenshot.png`. If the `filename` argument is present, it will write `screenshot-<FILENAME>.png`, where `<FILENAME>` is the value of `filename`. This enables multiple screenshots during a single test run—sort of like a graphical `printf` tracing statement.
=> end-to-end: takeScreenshot takes optional filename

lib/index.js, tests/server/app-test.js
This will be used to provide a "logged in as" indicator and to retrieve the user's list of URLs.
=> server: Add /id route to get logged-in user ID

public/app.js, public/index.html, public/tests/tests.js, tests/end-to-end/end-to-end.js
Required returning a Promise from `urlp.loadApp`, since we're fetching the user ID asynchronously. If network overhead is ever an issue, we can consider rendering index.html as a template, or sending back the logged-in user in an HTTP header.
Also, while experimenting with new end-to-end test cases, I realized that calling `driver.close()` would actually end the Chrome session, so the second commit removes that call from `afterEach`.
=> Add logged in user, logout link

public/app.js, public/index.html, public/tests/tests.js
Previously the view wouldn't change if there was content already present in the view-container. Also updates the nav links to set "New link" to `/#` and to use nonbreaking spaces between anchor text words.
=> public: Show landing view on empty hash change

public/index.html
Since we're focusing elements automatically using JavaScript, and ordering keeping the markup clean to begin with, setting the tabindex attribute is unnecessary.
=> public: Remove tabindex attributes

public/app.js, public/index.html, public/tests/tests.js
This is in anticipation of flashing the result of a delete operation inline in the "My links" table.
This also extracts the `prepareFlashingElement` test helper and pared down the number of `createLinkClick` test cases, since the `flashResult` test cases cover every condition at a lower level.
Also removes the 'button' class from button elements. It's redundant and unnecessary, since Skeleton CSS styles the buttons based on tag name to begin with.
=> Extract cl.flashResult

public/app.js, public/tests/tests.js, tests/end-to-end/end-to-end.js
These functions will be used to implement the upcoming delete API handler.
This change pares down the number of `createLink` test cases, since the `apiErrorMessage` test cases cover every API failure condition at a lower level.
Also, calling `event.preventDefault()`  is apparently more conformant to the DOM Events standard than returning `false`.
=> Extract createLinkInfo and apiErrorMessage, and use preventDefault() in onclick

public/app.js, public/index.html, public/tests/tests.js
As it turns out, the `XMLHttpRequest.onerror` handler won't handle `net::ERR_CONNECTION_REFUSED` or other network errors. For that, one needs to check for `xhr.status === 0` after `xhr.readyState === 4`.
The problem manifest when manually testing to simulate a link deletion request failure by killing the server, and there was no accompanying error message as expected from the `onerror` handler. The hint for the solution came from:
https://stackoverflow.com/questions/28556398/how-to-catch-neterr-connection-refused
This PR also contains commits for:
* Trimming leading slashes in createLinkInfo, as leading slashes from the "My links" table were causing problems.
* Removing the link from the "New link" form's failure message prefix, as it proved actually kind of clunky, especially when the …
=> Handle net::ERR_CONNECTION_REFUSED in XHR and other small fixups

public/app.js, public/tests/tests.js
This factors out the necessary calls to cl.flashResult() and Dialog.close() after both successful and unsuccessful API calls.
=> public: Add Dialog.doOperation

public/index.html
The result success/failure divs now take up 100% of their parent's width and contain center-aligned text.
The removal of the `button` classes should've been included in 560aad5 from #97.
=> public: Minor style touch-ups

public/app.js, public/tests/tests.js, tests/end-to-end/end-to-end.js
The `View` class makes the object expected by `showView` a bit more self-documenting.
The `Backend` class encapsulates all the details of API requests and response handling so that the user interface functions don't need to manage them any longer.
Replacing calls to `cl.xhr` with calls to `cl.backend` was a case where having the end-to-end tests paid off; it caught the fact that `cl.userId` wasn't getting set properly after getting all of the browser-only tests to pass.
=> Add View and Backend classes

public/app.js, public/tests/tests.js
Now that API success and error handling messages will be encapsulated within `Backend` functions, we can make `Dialog.doOperation` much more lightweight.
=> public: Prepare Dialog.doOperation for Backend ops

public/app.js, public/tests/tests.js
After this change, dialog boxes to confirm API operations will only require a couple of lines of code.
=> public: Make Dialog set link text, click handler

public/app.js, public/tests/tests.js
In addition to adding a `data` parameter so that templates can specify variable elements with the `data-name` attribute, this change reorders the constructor arguments to the `resultElement` comes last. Possibly makes formating calls a bit more awkward, but semantically makes more sense to supply the template name, the template data, the operation callback, and the result flash element in that order.
Adds a test to codify existing behavior whereby a Dialog may be created with a single button with a class attribute of 'confirm cancel focused'.
=> Apply data in Dialog constructor

public/app.js, public/index.html, public/tests/tests.js, tests/end-to-end/end-to-end.js
Deleting a link dynamically updates this total on the "My links" page.
Also contains a bugfix for `cl.apiErrorMessage` whereby the JSON body of an error response wasn't parsed, causing `xhrOrErr.response.err` to result in a cryptic "Cannot read property 'replace' of undefined" error message.
=> Display the total number of "My links"

lib/index.js, public/app.js, public/index.html, public/tests/tests.js, tests/end-to-end/end-to-end.js, tests/server/app-test.js
When the user attempts to use a nonexistent link, the app will automatically open the create link form with that link filled in so that the user can easily create the new link right away.
The backend required a small tweak to update the hash parameter.
=> public: Fill in create link form with unknown link

lib/index.js, public/app.js, public/index.html, public/tests/tests.js, tests/end-to-end/end-to-end.js, tests/server/app-test.js
This seems to make more sense, as the anticipated default use case for the root URL is to see a list of existing links owned by the user. This is compounded by the fact that accessing a nonexistent link will automatically open the "New link" view.
Required updating the browser tests such that `cl.userId` is set and `cl.backend.getUserInfo` is stubbed in the top-level `beforeEach`. Took the opportunity to add `USER_ID` everywhere as well.
=> Make "My links" the default landing page

public/app.js, public/index.html, public/tests/tests.js
This seems like generally useful information. A future change will make the links table sortable by link, target, created timestamp, updated timestamp, and clicks.
=> public: Show created, updated timestamps

public/app.js, public/tests/tests.js
This is in preparation for the edit link view, which will cause a redirect and return a rejected Promise under certain conditions.
=> public: Handle view function rejection in showView

public/app.js, public/tests/tests.js
This eliminates the need for callers to call JSON.parse on API responses.
=> public: Set json responseType for /api XHRs

lib/redis-client.js, public/app.js, public/tests/tests.js, tests/server/app-test.js, tests/server/link-db-test.js, tests/server/redis-client-test.js
This makes it consistent with the use of the term 'clicks' in the user interface, which is a bit more clear than 'count' when describing the number of times a link has been used.
=> Rename 'count' field to 'clicks'

public/app.js, public/index.html, public/tests/lib.js, public/tests/tests.js
This view will eventually enable the user to update the target URL of an existing link, or to assign the link to a new owner. This change contains the main view elements, but the button click handlers that will provide the actual behavior will be implemented in a future commit.
=> public: Add inactive link editing view

public/app.js, public/tests/tests.js
This new function eliminates some common boilerplate across backend calls and simplifies testing, i.e. we only have to check the args that each Backend function passes to Backend.makeApiCall, not the success and failure response for each function.
A future commit will change the remaining Backend member functions to use Backend.makeApiCall, since they currently behave slightly differently.
Also contains a commit to replace `HOST_PREFIX` in `public/tests/tests.js` with `window.location.origin`. Considering that I'd used `window.location.origin` in other test cases, I don't know why I created `HOST_PREFIX` to begin with.
=> Add Backend.makeApiCall

public/app.js, public/tests/tests.js
This contains a few minor updates in preparation for the edit link view:
* All button click handlers call `preventDefault` on the click event.
* The `validateTarget` function provides client-side URL validation.
* `createClickHandler` passes through a `data` argument.
* `stubCreateClickHandler` allows for validation of `createClickHandler` calls without executing the actual handler.
* The `createClickHandler` test constructs its own test elements rather than executing the `createView` click handler.
=> public: Refactor handlers, extract validateTarget

.gitignore, go, scripts/serve
Rather than require that the user always start redis-server separately, the `./go serve` command will attempt to launch it automatically if it isn't already running. Stoping the `./go serve` script with CTRL-C will also automatically stop the redis-server.
Also contains tweaks to the header comment for the ./go script itself.
=> Launch redis-server by default from `./go serve`

lib/config.js
On Alpine Linux, the 'fails to launch due to missing variables' test case from `tests/server/smoke-test.js` would intermittently fail due to the error message not containing the result of the `errors.join` expression. It would seem that the runtime failed to evaluate the temporary expression to build the error message string before passing it to the Error constructor.
While this seems like a platform bug with Node.js on Alpine/musl libc, the workaround is trivial.
=> Build err message before throwing Error from Config

lib/config.js, tests/helpers/env-vars.js, tests/helpers/index.js, tests/server/config-test.js, tests/server/smoke-test.js
This seems a bit more in line with the principle of least surprise. Also extracts the `EnvVar` helper class from the `Config` test for reuse in the smoke test.
=> Allow env vars to override config file

index.js, lib/config.js, tests/server/config-test.js
This is in anticipation of running the server in a container or any other environment in which redis is running on another host.
=> config: Add REDIS_HOST configuration variable

index.js, tests/server/smoke-test.js
Updates the main program in `index.js` to begin listening for requests only after the `RedisClient` emits a `ready` event. Without this change, the new test case would fail, as the `custom-links listening on port ...` message would get emitted before any error message due to a failure to connect to Redis.
=> main: Wait for Redis to be ready before listening

scripts/serve
redis-server instances launched automatically via `./go serve` would previously not flush their databases to disk before exit, resulting in updates disappearing between short-lived runs.
=> Shut down redis-server properly on exit from `./go serve`

.gitignore, scripts/lib/config-json, scripts/serve, scripts/setup, scripts/test, scripts/test.d/scripts, tests/scripts/environment.bash, tests/scripts/serve.bats
This is part one of improved shutdown handling; part two will come in a future commit involving a more graceful shutdown of the main node process itself.
I began to notice that running `./go serve` to launch the redis-server, using the app, and then killing the script quickly resulted in data loss. This didn't happen when running redis-server manually, as a signal sent to that process would result in it saving its data before exiting. The problem appeared to be that signals sent to the `./go serve` script would be sent simultaneously to the redis-server process, under which circumstances it wouldn't save its data automatically.
The script now launches redis-server in a separate process group so that any signals sent to the script aren't sent to the redis-server process. The custom-links …
=> serve: Ensure redis-server saves after signal

.config/karma.conf.js, package-lock.json, package.json, scripts/test, scripts/test.d/browser, tests/end-to-end/end-to-end.js
Per:
* https://developers.google.com/web/updates/2017/04/headless-chrome
* https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
Also keeping an eye on headless Firefox, which looks like it's coming soon:
* https://adriftwith.me/coding/2017/04/21/headless-slimerjs-with-firefox/
Once that's available, we can drop `xvfb` from `.travis.yml`.
Also includes updates to package-lock.json and enables Karma to run Chrome on CI/Travis again. If the latter update breaks the build due to the "Some of your tests did a full page reload!" bug again, I'll revert that commit.
=> Use headless Chrome on CI/Travis

.github/PULL_REQUEST_TEMPLATE.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
Closes #147.
Per mbland/cla#2, I've opted to note the GitHub Terms of Service regarding contribution licensing rather than using my own Contributor Licensing Agreement for now.
Also adds a code of conduct and a pull request template.
=> Add CONTRIBUTING.md guidelines; note GitHub ToS

README.md, lib/config.js, tests/server/config-test.js
In addition to converting authenticated user IDs to lowercase in #155 and #156, it seems prudent to ensure that configured user IDs and domains are all forced to lowercase as well, to adhere to the principle of least surprise.
=> config: Convert users and domains to lowercase

tests/server/smoke-test.js
The previous implementation relied on failure due to a bad Redis host name. This worked most of the time, but while running the test suite in a coffee shop, this test case would timeout and leave a stale redis-server running in the background. Eventually I realized this was because the coffee shop DNS provider was converting failed name lookups to search queries.
This implementation instead relies on connecting to an unused port, and doesn't start a redis-server instance to begin with.
cc: @akashvbabu @mpdatx
=> Fix "bad Redis" failure case flakiness

index.js, lib/config.js, lib/redis-client.js, tests/end-to-end/end-to-end.js, tests/server/config-test.js, tests/server/redis-client-test.js
Part of #160, #161, #165, and #166. Implements the RedisClient operations necessary to support these search, autocomplete, and target collision features.
Uses the lexicographic completion approach described in: http://oldblog.antirez.com/post/autocomplete-with-redis.html
Note that we'll need a migration script to create the new search indexes for existing installations.
=> redis: Add link, target completion & target search

lib/link-db.js, lib/redis-client.js, tests/server/link-db-test.js, tests/server/redis-client-test.js
Adds `deindexLink()` and `reindexLink()` methods to `RedisClient`, as well as moves the previously private `addLinkToSearchSets()` to `RedisClient.indexLink()`.
This also renames `LinkDb.checkOwnership()` to `LinkDb.getLinkIfOwner()`, which now returns the link info object it uses to validate ownership. This will make dispatching to the `RedisClient` indexing methods more efficient.
The next PR will do some more refactoring between `RedisClient` and `LinkDb` in an effort to better separate concerns.
=> Deindex and reindex links

lib/link-db.js, tests/server/link-db-test.js
The first problem with the previous implementation (other than we forgot to test it) was that the underlying RedisClient.searchShortLinks() was already returning linkInfo objects. Consequently, the call to RedisClient.fetchLinkData() was not only superflouous, but causing server errors, because it expects an array of strings, not an array of objects.
The second problem was that it returned an array, passed through the API as a JSON array, which has presented various security vulnerabilities over time (do a quick search on "json array security"). Wrapping arrays in an object is still recommended by OWASP:
https://www.owasp.org/index.php/AJAX_Security_Cheat_Sheet#Always_return_JSON_with_an_Object_on_the_outside
=> LinkDb: Fix searchShortLinks, return object

.istanbul.yml, bin/run-migrations, lib/redis/migrations/0000-target-search-autocomplete.js
The migration script builds the autocomplete and target URL indexes from the existing data. New custom links will be indexed by the server automatically. This script is idempotent, so running it multiple times will not have an impact on the consistency of the database.
The `run-migrations` script allows for multiple migrations to run in the future.
While I don't have tests for these new scripts, the underlying classes they use are the same as those used by the Custom Links server itself, and are thoroughly tested. (Still, I feel like I should have some...I'll create a tech debt ticket if asked!)
=> Migration for autocomplete, target URL indexes

public/app.js, public/index.html, public/tests/tests.js, tests/end-to-end/end-to-end.js
Closes #161, #165. It's rudimentary, but enables the user to search by both custom links and their target URLs.
Since the underlying database is Redis, it accepts any glob-style pattern that can be passed as an argument to scan().
cc: @unhuman, @mpdatx
=> Add the search user interface

lib/index.js, lib/link-db.js, tests/server/app-test.js
Part of #160. This is more or less a straight passthrough to LinkDb.completeLink(), which passes through to RedisClient.completeLink().
Also moved the `/api/search` test to be part of the `API` block, and tweaked the error path in that API endpoint to avoid emitting `Cannot read property 'then' of undefined` output, as in:
https://travis-ci.org/mbland/custom-links/jobs/371712950
=> API: Add /autocomplete endpoint

Dockerfile, package-lock.json
There are no feature changes in this commit, only dependency updates and a bump to Node.js 10.0.0 for the Docker image.
Note that the new package-lock.json was generated with npm v6.0.0, and contains the custom-links 0.2.1 version bump that should've been included in v0.2.1.
=> Update npm versions, Node.js 10.0.0-alpine
