lib/redirect-db.js
lib/redis-client.js
tests/redirect-db-test.js
tests/redis-client-test.js

This is in preparation for supporting authentication via [passport](https://www.npmjs.com/package/passport).

Add user creation and integrity checks

---

lib/auth.js
lib/redirect-db.js
tests/auth-test.js
tests/redirect-db-test.js

These are in preparation for adding [passport](http://passportjs.org/) support. The `verifyGoogle` function is specifically for [passport-google-oauth20](https://github.com/jaredhanson/passport-google-oauth2) support.

Add Passport authentication helper functions

---

.gitignore
config.json
index.js
lib/config.js
tests/config-test.js
tests/helpers/index.js
tests/helpers/test-config.json

Ensures that the system configuration is complete and well-formed.

Add Config class

---

config.json
lib/auth.js
lib/config.js
tests/config-test.js
tests/helpers/test-config.json

Seemed like a good idea to support multiple different providers, and
possibly more than one simultaneously.

Config: Enable multiple providers

---

lib/auth.js
lib/auth/google.js
lib/config.js
tests/auth-test.js

The idea is that supported providers will each have a module under `lib/auth` wherein its config fields and verification functions will be defined.

Extract lib/auth/google module

---

lib/auth.js
lib/auth/google.js
lib/auth/test.js
lib/config.js
lib/index.js
package.json
tests/app-test.js
tests/auth-test.js
tests/config-test.js
tests/helpers/test-config.json

This is in preparation for integrating [passport](http://passportjs.org/) authentication.

Test and Google auth strategies and session configuration

---

lib/index.js
package.json
tests/app-test.js

This is the first POST method implemented.

Add /create handler to API

---

lib/index.js
tests/app-test.js

Adds `/user`, `/owner`, `/location`, and `/delete`.
After this, it's time to implement the user interface.

Complete the remaining API methods

---

tests/smoke-test.js

This should help reduce flakiness due to Travis server load.

smoke-test: Increase setup timeouts to 5000ms

---

package.json
scripts/serve

Also implements tab completion and uses test-config.json as a default for running index.js.

scripts/server: Enable UI-only live-server

---

.eslintignore
public/app.js
public/index.html
public/tests/index.html
public/tests/lib.js
public/tests/tests.js
public/tests/vendor/chai.js
public/tests/vendor/mocha.css
public/tests/vendor/mocha.js
scripts/lint

This is in preparation for fleshing out the UI with Mocha tests.

Add initial app lib, mocha.js browser fixture

---

public/app.js
public/index.html
public/tests/tests.js

This introduces the beginning of the single-page app template system, including the `applyData` function for binding values to template elements.

Create views from templates and bind data to them

---

public/app.js
public/tests/tests.js

In preparation for flashing success and failure messages when creating or updating a link.

app: Implement flashElement

---

public/app.js
public/tests/tests.js

The next commit will use this function to implement the click handler.

app: Add createLink() API request implementation

---

public/app.js
public/tests/tests.js

While beginning to work on the `createLinkClick()` function, I realized that POSTing to the local live-server instance produced a 405 without a JSON body; added logic to handle this, refactoring the existing logic in the process.
Also, after early experimentation with creating an actual short link via the user interface, realized it would be good to include the anchor for the generated link in both the success and error responses.

createLink: Include anchor, handle test server 405

---

package.json
public/app.js
public/index.html
public/tests/tests.js
scripts/test.d/end-to-end
tests/end-to-end.js

This test isn't set up to run in Travis, and is far from complete, but demonstrates that the test harness starts the local servers and can correctly drive browsers via the selenium-webdriver package. Much more to come!
Also contains a small tweak to change the form button name to 'submit'.

Add first work-in-progress end-to-end test

---

index.js
lib/auth.js
lib/auth/google.js
lib/config.js
lib/index.js
lib/redirect-db.js
lib/redis-client.js
tests/end-to-end/end-to-end.js
tests/helpers/index.js

This is purely a stylistic update; no behavior has changed at all.
The code in `public/` remains the same, as PhantomJS won't support ES6 until the upcoming 2.5.0 release.

Use ES6 arrow callbacks, object literal functions

---

tests/end-to-end/end-to-end.js

Previously the `driver.quit()` call was in `afterEach` and the redis database wasn't cleaned up after each test case.

end-to-end: Cleanup redis, close window, quit last

---

lib/redirect-db.js
tests/server/redirect-db-test.js

This can be helpful in negotiating with someone to update or transfer ownership of a link.

RedirectDb: Show existing url owner if other user

---

README.md
index.js
lib/auth/test.js
lib/config.js
package-lock.json
package.json
public/index.html
public/tests/tests.js
tests/helpers/index.js
tests/server/app-test.js
tests/server/auth-test.js
tests/server/config-test.js
tests/server/smoke-test.js

This is a less technical, more descriptive name.

Rename from URL Pointers to Custom Links

---

.travis.yml

Should've been part of #85. Using `travis encrypt ... --add` also stripped the extra newlines.

travis: Update CODECLIMATE_REPO_TOKEN

---

index.js
public/app.js
public/index.html
public/tests/lib.js
public/tests/tests.js
scripts/lib/coverage
scripts/serve
scripts/setup
scripts/test
scripts/test.d/browser
scripts/test.d/server

Change [Uu][Rr][Ll][Pp] prefixes to [Cc][Ll]

---

public/app.js
public/tests/lib.js
public/tests/tests.js

This is in anticipation of creating the "My links" view.
Also extracts `clTest.createVisibleElement` and `clTest.removeElement`.

public: Add createAnchor, focusFirstElement

---

public/app.js
public/tests/tests.js

This is in anticipation of having the view rendering functions it invokes also return Promises.
Also contains:
* Return a Promise from `landingView`
* Push empty hash check to top of `showView`
* Creates `UNKNOWN_USER` constant

Refactor showView() to return a Promise

---

public/app.js
public/index.html
public/tests/tests.js

A future commit will add an end-to-end test or two.

public: Add a responsive "My links" view

---

tests/end-to-end/end-to-end.js

As promised by the earlier commit from #94.

e2e: Add tests for logout, "My links" view

---

public/app.js
public/index.html
public/tests/tests.js

This is more proper according to:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a#Accessibility_recommendations
Also split each CSS rule onto a separate line, because splitting them apart each time they need to be edited is madness.

public: Use buttons for "My links" edit, delete

---

public/app.js
public/index.html
public/tests/tests.js

This provides the support for the upcoming delete link confirmation dialog. Design and behavior inspired by:
* https://bitsofco.de/accessible-modal-dialog/
* https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_dialog_role

public: Add Dialog class for modal dialog boxes

---

public/app.js
public/tests/tests.js

Also extracts the `cl.rejectOnApiError` helper function.

public: Add Backend.deleteLink

---

public/app.js
public/index.html
public/tests/tests.js
tests/end-to-end/end-to-end.js

Clicking "Yes" will launch the API call to delete the chosen link. The corresponding row will flash with the result of the operation.

Add delete link confirmation dialog

---

lib/index.js
lib/redirect-db.js
lib/redis-client.js
public/app.js
public/index.html
public/tests/tests.js
tests/end-to-end/end-to-end.js
tests/server/app-test.js
tests/server/redirect-db-test.js
tests/server/redis-client-test.js

This is to match the terminology of the project itself ("Custom Links") and that of the "create new link" form.

Replace "URL/url/redirection" with "link"

---

index.js
lib/auth.js
lib/auth/google.js
lib/auth/test.js
lib/index.js
lib/link-db.js
tests/server/app-test.js
tests/server/auth-test.js
tests/server/link-db-test.js

As with commit 7fa7ca9d from #112, this is to match the terminology of the project itself ("Custom Links").

Rename RedirectDb to LinkDb

---

lib/index.js
lib/link-db.js
lib/redis-client.js
public/app.js
public/index.html
public/tests/tests.js
tests/server/app-test.js
tests/server/link-db-test.js
tests/server/redis-client-test.js

As with commit 7fa7ca9d from #112, this is to match the terminology of the project itself ("Custom Links") and that of the "create new link" form.

Replace "location" with "target"

---

index.js
lib/redis-client.js
tests/server/app-test.js
tests/server/redis-client-test.js

This information will get surfaced in an update to the "My links" page.

Store creation and update timestamps

---

public/app.js
public/index.html
public/tests/tests.js

This is the first step towards making the "My links" view the landing page view.

Replace landing-view with create-link view

---

public/app.js
public/index.html
public/tests/tests.js
tests/end-to-end/end-to-end.js

`cl.apiErrorMessage` was incorrectly calling `JSON.parse` on the already-parsed JSON response, resulting in the error message: "Unexpected token o in JSON at position 1"

public: Fix error response handling bug

---

public/app.js
public/tests/tests.js

Contains a number of changes done to support the upcoming link editing view that have been split out to keep that commit more focused.
Also contains the new `cl.errorView` function which will flash errors when the edit link view can't be shown.

public: Refactor in preparation for edit view

---

public/app.js
public/tests/tests.js

This required downstream changes to cl.editLinkView and cl.linksView as well.

Update Backend.getLink and Backend.getUserInfo to use Backend.makeApiCall

---

public/app.js
public/tests/tests.js

This will be reused to provide the functionality for the edit link view.

Extract createClickHandler

---

public/app.js
public/index.html
public/tests/tests.js
public/tests/updated-target.html
tests/end-to-end/end-to-end.js

This enables the user to update the target URL of an existing link, or to assign the link to a new owner. All of the major functionality of the application is now complete.

public: Add link editing view

---

README.md

There should now be sufficient information for a potential user or contributor to get a Custom Links server instance up and running.
@eljobe please ping me or file an issue if anything is confusing or incomplete, or if you have suggestions for improvement!

README: Document installation, config, development

---

index.js
package-lock.json
package.json

This provides timestamped log output. Also, the package-lock.json file has been updated via npm v5.3.0.

Use log package instead of console in main program

---

lib/auth/openidconnect.js
lib/config.js
package.json
tests/server/auth-test.js

- [X ] I have reviewed the [contributor guidelines][contrib].
- [X ] I have reviewed the [code of conduct][conduct].
contribution under the same terms as [this project's license][license], and
that I have the right to license my contribution under those terms.
[contrib]: https://github.com/mbland/custom-links/blob/master/CONTRIBUTING.md
[conduct]: https://github.com/mbland/custom-links/blob/master/CODE_OF_CONDUCT.md
[gh-tos]:  https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license
[license]: https://github.com/mbland/custom-links/blob/master/LICENSE.md
cc: @mbland

Added open-id Okta integration

---

.dockerignore
.gitignore
Dockerfile
docker-compose.yml
go
package.json

This enables the building of a complete, functional Docker image, as well as bringing the system up locally with `docker-compose`.
Also updated the `./go` script with updates from `go-template` in v1.7.0 and set the `package.json` version to v0.1.0, since I plan to cut a release soon, before all the v1.0.0 features are finished.

Add Dockerfile and docker-compose.yml

---

lib/auth.js
tests/server/auth-test.js

auth: Convert all user IDs to lowercase

---

package-lock.json
package.json

`./go test end-to-end` was failing with the latest Chrome 66.0.3359.117. Updating the packages resolved all the issues.
cc: @akashvbabu

Update to latest npms, incl. mocha-chrome 1.1.0

---

lib/index.js
lib/link-db.js
tests/server/app-test.js
tests/server/link-db-test.js

- [ Yes ] I have reviewed the [contributor guidelines][contrib].
- [ Yes ] I have reviewed the [code of conduct][conduct].
- [ Yes ] Per [GitHub's Terms of Service][gh-tos], I am aware that I license my
contribution under the same terms as [this project's license][license], and
that I have the right to license my contribution under those terms.
[contrib]: https://github.com/mbland/custom-links/blob/master/CONTRIBUTING.md
[conduct]: https://github.com/mbland/custom-links/blob/master/CODE_OF_CONDUCT.md
[gh-tos]:  https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license
[license]: https://github.com/mbland/custom-links/blob/master/LICENSE.md
cc: @mbland

added api for searching and Mike's refactor for search helpers
